# Generated by Django 5.1 on 2024-08-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='max_patients',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
