# Generated by Django 5.1 on 2024-08-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmenthistory',
            name='treatment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
